# Generated by Django 3.0.2 on 2020-03-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200303_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Dirección Web'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='description',
            field=models.TextField(default='', verbose_name='Descripción'),
        ),
    ]
